version: '3'
services:

  mysql:
    image: mysql
    
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_HOST=%
      
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./my-db:/var/lib/mysql

  java:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      - mysql